#!/bin/sh
mkdir -p lib
cd lib
wget https://github.com/inspircd/inspircd/archive/v3.3.0.tar.gz
tar -xvf v3.3.0.tar.gz
rm v3.3.0.tar.gz
cd inspircd-3.3.0
#./configure --enable-extras=m_pgsql.cpp --enable-extras=m_ssl_openssl.cpp
echo "no
yes
no
no
no
yes
no
no
no
no
no
no
no
no
yes
yes
no" | ./configure
make -j8 install
