satyr:
  name: '<iname>'
  domain: '<domain>'
  email: '<email>'
  registration: false

media:
  record: false
  ffmpeg: '<ffmpeg>'

rtmp:
  port: 1935

http:
  # uncomment to set HSTS when SSL is ready
  #hsts: true

database:
  user: '<dbuser>'
  password: '<dbpass>'
  database: '<dbname>'
  host: '<dbhost>'

transcode:
  adaptive: false
  format: dash
  variants: 3

chat:

  irc:
    enabled: false
    server:
    port: 6667
    tls: false
    nickname: 'SatyrChat'
    username: 'SatyrChat'
    realname: 'Satyr Chat Integration Bot'
    sasl: false
    password:

  discord:
    enabled: false
    token:
    #server name is optional, will relay from messages from all matching channels in all servers
    #if not specified
    server:

  xmpp:
    enabled: false
    server:
    port: 5222
    nickname: 'SatyrChat'
    username: 'SatyrChat'

  twitch:
    enabled: false
    username:
    token: