satyr:
  name: '<iname>'
  domain: '<domain>'
  email: '<email>'
  registration: false

media:
  record: false
  ffmpeg: '<ffmpeg>'

rtmp:
  port: 1935

http:
  # uncomment to set HSTS when SSL is ready
  #hsts: true

database:
  user: '<dbuser>'
  password: '<dbpass>'
  database: '<dbname>'
  host: '<dbhost>'

transcode:
  #may result in higher latency if your cpu can't keep up
  adaptive: false
  variants: 3
  #unused right now, will always transcode to dash
  format: dash

chat:

  irc:
    enabled: false
    server:
    port: 6667
    tls: false
    nickname: 'SatyrChat'
    username: 'SatyrChat'
    realname: 'Satyr Chat Integration Bot'
    sasl: false
    password:

  discord:
    enabled: false
    token:

  xmpp:
    enabled: false
    server:
    port: 5222
    nickname: 'SatyrChat'
    username: 'SatyrChat'

  twitch:
    enabled: false
    username:
    #https://twitchapps.com/tmi/
    password: