satyr:
  name: '<iname>'
  domain: '<domain>'
  email: '<email>'
  registration: false

media:
  record: false
  ffmpeg: '<ffmpeg>'

rtmp:
  # enable cluster mode this will pretty much entirely
  #  break the ability to play rtmp for clients
  cluster: false
  port: 1935

http:
  # uncomment to set HSTS when SSL is ready
  #hsts: true
  server_side_render: false

database:
  user: '<dbuser>'
  password: '<dbpass>'
  database: '<dbname>'
  host: '<dbhost>'

transcode:
  #may result in higher latency if your cpu can't keep up
  adaptive: false
  variants: 3
  #unused right now, will always transcode to dash
  format: dash

hwaccel:
  # see docs/HWACCEL.md for instructions on configuring hardware acceleration
  type: null

chat:

  irc:
    enabled: false
    server:
    port: 6667
    tls: false
    nickname: 'SatyrChat'
    username: 'SatyrChat'
    realname: 'Satyr Chat Integration Bot'
    sasl: false
    password:

  discord:
    enabled: false
    token:

  xmpp:
    enabled: false
    server: 
    port: 5222
    jid: 
    password: 
    nickname: 

  twitch:
    enabled: false
    username:
    #https://twitchapps.com/tmi/
    password:

twitch_mirror:
# enable to allow users to mirror video streams to twitch
# for those with truly no bandwidth limits
  enabled: false
  # https://stream.twitch.tv/ingests/
  # do not include {stream_key}
  ingest: 'rtmp://live-ord02.twitch.tv/app/'