[satyr]
name = '<iname>'
domain = '<domain>'
email = '<email>'
registration = false

[media]
record = false
ffmpeg = '<ffmpeg>'

[server.http]
# uncomment to set HSTS when SSL is enabled
# hsts = true

[database]
user = '<dbuser>'
password = '<dbpass>'
database = '<dbname>'
host = '<dbhost>'
